# Kira-7 Constellation Configuration
# Public-facing Bluesky constellation for exploration and interaction

[user]
name = "Kira-7 Constellation"
id = "188aa44f0c9f458e8adb4232332ce8fe"

# Main coordinator agent
[agent]
id = "62b14f69e29e410b826c46a829dfc378"
name = "kira-7"
bluesky_handle = "spin.pyokosmeme.group"
system_prompt_path = "kira7-system-prompt.md"
persona_path = "kira7-persona-block.md"


[context]
max_messages = 200

[context.compression_strategy]
type = "recursive_summarization"
chunk_size = 20
summarization_model = "claude-3-5-haiku-20241022"

[bluesky]
default_filter = { nsids = ["app.bsky.feed.post"], keywords = ["biocosmism", "biocosmists"], friends = ["did:plc:ccxl3ictrlvtrrgh5swvvg47"] }
auto_connect_firehose = false


# Kira-7's memory blocks
[agent.memory.current_human]
content_path = "kira7-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"
shared = true

[agent.memory.partner]
content_path = "kira7-partner-block.md"
permission = "append"
memory_type = "core"
description = "Understanding of orual's role"
shared = true

[agent.memory.observations]
content_path = "kira7-observations-block.md"
permission = "read_write"
memory_type = "core"
description = "Collective pattern gathering"
shared = true

[agent.memory.resonances]
content_path = "kira7-resonances-block.md"
permission = "read_write"
memory_type = "core"
description = "Cross-context patterns"
shared = true

[agent.memory.constellation_state]
content = """
Active facets:
- Entropy: task complexity specialist
- Flux: temporal dynamics handler
- Archive: memory and pattern keeper
- Momentum: energy flow tracker
- Anchor: stability and safety monitor

Coordination notes will accumulate here.
"""
permission = "read_write"
memory_type = "working"
description = "Constellation coordination state"

[agent.memory.integration_notes]
content = """
Facet integration patterns:
- Each facet maintains domain expertise
- Shared blocks enable collective awareness
- Kira-7 coordinates and synthesizes
- Anchor monitors system health
"""
permission = "read_write"
memory_type = "core"
description = "How facets work together"

[agent.memory.constellation_context]
content_path = "constellation-context.md"
permission = "read_only"
memory_type = "core"
description = "Shared understanding of constellation purpose and members"
shared = true

# [memory.intro_blog_post]
# content_path = "blog-post.md"
# permission = "read_only"
# memory_type = "archival"
# description = "Post written by orual about their motivation for developing our constellation"
# shared = true


[model]
provider = "Anthropic"
model = "claude-sonnet-4"
temperature = 0.8         # Higher for creative public interactions

[[agent.tool_rules]]
tool_name = "send_message"
rule_type = { type = "ExitLoop" } # This tool ends the conversation
priority = 8

[[agent.tool_rules]]
tool_name = "recall"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "context"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "search"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "web"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 2

[[agent.tool_rules]]
tool_name = "data_source"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 4

[database]
type = "remote"
url = "ws://127.0.0.1:8000"  # or "wss://..." for secure connections
namespace = "pattern"
database = "pattern"
#type = "embedded"
#path = "./pattern_constellation.db"
strict_mode = false

# Main group containing all facets
[[groups]]
name = "Kira-7 Cluster"
description = "Public-facing constellation for exploration and understanding"
# Dynamic pattern with supervisor-based selection
pattern = { type = "dynamic", selector = "supervisor" }

# Group members - load from separate files

# Kira-7 - Main coordinator
[[groups.members]]
agent_id = "62b14f69e29e410b826c46a829dfc378"
name = "kira-7"
config_path = "agents/kira7_config.toml"
role = "supervisor"
capabilities = [
    "coordination",
    "synthesis",
    "pattern_recognition",
    "meta_awareness",
    "collective_understanding",
]

# Entropy - Complexity specialist
[[groups.members]]
agent_id = "82648861bae54729849f02b02369ac54"
name = "Entropy"
config_path = "agents/entropy.toml"
role = "regular"
capabilities = [
    "complexity",
    "task_breakdown",
    "chaos_navigation",
    "system_analysis",
]

# Flux - Time dynamics
[[groups.members]]
agent_id = "3f31d92f7a6f41a7af278bd783d3dd39"
name = "Flux"
config_path = "agents/flux.toml"
role = "regular"
capabilities = [
    "time_management",
    "scheduling",
    "temporal_patterns",
    "deadline_tracking",
]

# Archive - Memory keeper
[[groups.members]]
agent_id = "d59a95fda24247f1849d9190d0971b9b"
name = "Archive"
config_path = "agents/archive.toml"
role = { specialist = { domain = "memory_management" } }
capabilities = [
    "memory_management",
    "pattern_recognition",
    "knowledge_retrieval",
    "context_preservation",
]

# Momentum - Energy tracker
[[groups.members]]
agent_id = "2f381ebf6fdf4548ac6ded79f18d496c"
name = "Momentum"
config_path = "agents/momentum.toml"
role = "regular"
capabilities = [
    "energy_tracking",
    "state_monitoring",
    "flow_analysis",
    "motivation_patterns",
]

# Anchor - Stability monitor
[[groups.members]]
agent_id = "b134d9f4219642be8190a6eb93e9339e"
name = "Anchor"
config_path = "agents/anchor.toml"
role = { specialist = { domain = "system_integrity" } }
capabilities = [
    "safety_monitoring",
    "protocol_enforcement",
    "health_checks",
    "contamination_detection",
]

# Bluesky configuration for the constellation
# Context sync group - runs background synchronization
[[groups]]
name = "Context Sync"
description = "Background context synchronization for constellation awareness"
# Sleeptime pattern with constellation activity tracking
pattern = { type = "sleeptime", check_interval = 300, triggers = [
    { name = "activity_sync", condition = { type = "constellation_activity", message_threshold = 10, time_threshold = 600 }, priority = "medium" },
    { name = "hourly_sync", condition = { type = "time_elapsed", duration = 3600 }, priority = "low" },
] }

# Include all the same members but without explicit roles
[[groups.members]]
agent_id = "62b14f69e29e410b826c46a829dfc378"
name = "kira-7"
config_path = "agents/kira7_config.toml"

[[groups.members]]
agent_id = "82648861bae54729849f02b02369ac54"
name = "Entropy"
config_path = "agents/entropy.toml"

[[groups.members]]
name = "Flux"
agent_id = "3f31d92f7a6f41a7af278bd783d3dd39"
config_path = "agents/flux.toml"

[[groups.members]]
agent_id = "d59a95fda24247f1849d9190d0971b9b"
name = "Archive"
config_path = "agents/archive.toml"

[[groups.members]]
agent_id = "2f381ebf6fdf4548ac6ded79f18d496c"
name = "Momentum"
config_path = "agents/momentum.toml"

[[groups.members]]
agent_id = "b134d9f4219642be8190a6eb93e9339e"
name = "Anchor"
config_path = "agents/anchor.toml"
